@startuml
hide empty methods
allowmixing
'https://plantuml.com/sequence-diagram

' change the default colors for the classes
skinparam class {
BackgroundColor LightBlue
ArrowColor SeaGreen
BorderColor DarkBLue
}
skinparam packageStyle frame

title "<u>Process Flow for Laminator Report Generation"

' group the packages to push them toward being lined up
together {
    package material_defect_system #LightBlue {
        class material_defect_hmi {
            + show_popup
            + popup_interaction
            }
        class ignition_scada {
            + input
            + output
        }
        class defect_database {
            + input
            + output
        }
        class mahlo_scanner {
            measures thickness
        }
    }

    package original #ffc45e {
        class work_order {
            order details
        }

        class mahlo_report
        class operator
        class mahlo_hmi

        class pdf_reports
    }
    package report_automation #89b74b {
        class table_extractor {
            extract data from pdf tables
        }
        class renamer
        class excel_reports {
            Include PDF data, removal records,\nand SCADA tag history.
        }
    }
}

' define the defect popups
mahlo_scanner -[#BLue]> ignition_scada::input : "defect detected"
ignition_scada::output -[#BLue]|> defect_database::input
ignition_scada::output -[#BLue]|> material_defect_hmi::show_popup : "lam stopped"
material_defect_hmi::popup_interaction  <|-up[#BLue]-|> "confirm\nremoved" operator
defect_database <|-[#BLue]-|> material_defect_hmi::popup_interaction : update defect\ndata
'material_defect_hmi "update defect\n data" -[#BLue]-|> defect_database::input

'' the renaming and excel reports process
renamer <|-down[#Red]-|> "rename" pdf_reports
renamer -[#Red]|> table_extractor : "renamed\nlist"
table_extractor -[#Red]|> excel_reports
defect_database -[#Red]|> "include removal\ndata" table_extractor
ignition_scada "relevant tag\nhistory data" -[#Red]|> table_extractor

' d78048
' the original process to generate mahlo reports
work_order -[#d78048]> operator::input
operator::output -[#d78048]> mahlo_hmi::input
mahlo_hmi -[#d78048]> mahlo_report
mahlo_report -[#d78048]> pdf_reports



@enduml